import type { Metadata } from "next";
import { Geist, Azeret_Mono as Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "./components/ui/sidebar";
import AppSidebar from "./components/AppSidebar/AppSidebar";
import { Header } from "./components/Header/Header";
import { MainStoreProvider } from "./lib/StoreProvider";
import ReactQueryProviders from "./lib/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProviders>
      <html lang='en'>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SidebarProvider>
            <AppSidebar />
            <main className='flex-1'>
              <Header />
              <MainStoreProvider>{children}</MainStoreProvider>
            </main>
          </SidebarProvider>
        </body>
      </html>
    </ReactQueryProviders>
  );
}
